## 제10장 그래프 - 경로 탐색

### 1. 두 노드 사이의  경로 수  계산
####   그래프의 인접 행렬을 사용하여 그래프에서 두 노드 사이의 경로 수를 찾을 수 있습니다.
#### 다음 [그림 1]의 그래프를 통해서 각 노드간 경로 수 계산을 학습하여 봅시다. 
![Alttext](fig11-1.png)

#### 상기 [그림 1] 그래프의 인접노드 목록 표현은 아래와 같습니다.

In [1]:
adjL_s = {
       'B': ['F', 'L', 'N', 'S'],
       'E': ['F', 'L'],
       'F': ['B', 'E', 'L', 'N'],
       'L': ['B', 'E', 'F', 'N', 'S'],
       'N': ['B', 'F', 'L', 'S'],
       'S': ['B', 'L', 'N']  }

#### 또한 다음의 파이썬 함수를 통해, [그림  1] 그래프의  인접 행렬 표현을 구해봅시다.

In [2]:
def Adj_Mat(adjL):  
    n=len(adjL)
    nodes =list()    
    for key in adjL:
        nodes.append(key)
   #nodes=['B', 'E', 'F', 'L', 'N', 'S']
    adM= [[] for _ in range(n)]  # key 갯수와 같은 리스트 요소를 갖는 리스트 어레이 만듬  
    #adM=[[A],[],[],[],[],[],[]]
    k=0 # 인접행렬의 행 인덱스 [A]
    j=0  # 각 노드에 대해, 인접노드 목록에서 마지막 인접 노드 순번의  다음 차례
    for node in nodes:
        print("nodes=", nodes)
        print(type(nodes))
        if adjL[node]: #
            for s in adjL[node]: #(1);
                i=0  #노드 목록의 인덱스
               # print("node={}, str={}".format(node,s))
                while(i < n):                   
                    if i>=j:      #(2)                 
                        if s == nodes[i]:
                            adM[k].append(1)
                            j=i+1           
                            i=n
                        else:
                            adM[k].append(0)  
                            i+=1
                    else:
                        i+=1
            if j< n: #  (3)
                for _ in range(j, n):
                    adM[k].append(0)  
            
        else:
            for _ in range(n):
                adM[k].append(0)
        k+=1
        j=0
    return adM    

![Alttext](fig11_exp_1.png)

In [4]:
adjMatrix=Adj_Mat(adjL_s)
adjMatrix

nodes= ['B', 'E', 'F', 'L', 'N', 'S']
<class 'list'>
nodes= ['B', 'E', 'F', 'L', 'N', 'S']
<class 'list'>
nodes= ['B', 'E', 'F', 'L', 'N', 'S']
<class 'list'>
nodes= ['B', 'E', 'F', 'L', 'N', 'S']
<class 'list'>
nodes= ['B', 'E', 'F', 'L', 'N', 'S']
<class 'list'>
nodes= ['B', 'E', 'F', 'L', 'N', 'S']
<class 'list'>


[[0, 0, 1, 1, 1, 1],
 [0, 0, 1, 1, 0, 0],
 [1, 1, 0, 1, 1, 0],
 [1, 1, 1, 0, 1, 1],
 [1, 0, 1, 1, 0, 1],
 [1, 0, 0, 1, 1, 0]]

In [5]:
import numpy as np
MA=np.matrix(adjMatrix)
print(MA)
type(MA)

[[0 0 1 1 1 1]
 [0 0 1 1 0 0]
 [1 1 0 1 1 0]
 [1 1 1 0 1 1]
 [1 0 1 1 0 1]
 [1 0 0 1 1 0]]


numpy.matrixlib.defmatrix.matrix

In [6]:
MA[2,1]

1

In [7]:
MA*MA

matrix([[4, 2, 2, 3, 3, 2],
        [2, 2, 1, 1, 2, 1],
        [2, 1, 4, 3, 2, 3],
        [3, 1, 3, 5, 3, 2],
        [3, 2, 2, 3, 4, 2],
        [2, 1, 3, 2, 2, 3]])

####  그래프에서  노드 $v_i$ 에서  노드 $v_j$ 까지의 거리 $r$ 인 경로의 수 찾기는 
#### 인접행렬 $A$ 에 대해 $A^r $ 의 $(i,j)$ 요소의 값입니다. 

#### 상기 [그림 1] 에 대해,  노드  $S$ 에서 노드  $F$ 까지 의 최단거리를 구해 봅시다
####  이는 $A^r$  의 요소 $(i=5,j=2) $ (여기서, $i$와 $j$는 노드들을 $['B, 'E', 'F', 'L', 'N', 'S'] $ 로 정렬할 때, $S$ 및 $F$의  위치 . 즉, $i=5$, $j=2$ 가 됨 ) 가 처음으로 0 아 인, $r$ 값이 최단 거리가 되며, 이때의  $A^r (i,j)$ 의 값이 경로의 수가 된다. 

In [8]:
def Matrix_Mul(A,r):
    if r==0:
        return 1
    if r==1:
        return A
    return Matrix_Mul(A,r-1)*A

In [9]:
aa=Matrix_Mul(MA,2)
type(aa)

numpy.matrixlib.defmatrix.matrix

In [10]:
import numpy as np
def find_shortest_dist(AdjM, nodes, start, end, Max=10):
    if start==end:
        return 0
    start_int=0
    end_int=0
    MA=np.matrix(AdjM)    
    NS=set(nodes)
    if start not in nodes or end not in nodes:
        return None
    NL=list(nodes)
    NL.sort()
    i=0
    for i, node in enumerate(NL):
        if node==start:
            start_int=i
        if node ==end:
            end_int=i
    for r in range(1, Max+1):
        A_r = Matrix_Mul(MA, r)
        if A_r[start_int, end_int]!=0:
            print(A_r) 
            val=A_r[start_int, end_int]            
            return print("최단 경로 길이는 {} 이며, 길이 {}인 경로가 {}개 있다.".format(r, r, val))     
        

In [11]:
nodes={'B', 'E', 'F', 'L', 'N',  'S' } 
find_shortest_dist(adjMatrix, nodes, 'S', 'F')

[[4 2 2 3 3 2]
 [2 2 1 1 2 1]
 [2 1 4 3 2 3]
 [3 1 3 5 3 2]
 [3 2 2 3 4 2]
 [2 1 3 2 2 3]]
최단 경로 길이는 2 이며, 길이 2인 경로가 3개 있다.


##  2. 경로 찾기
### 다음으로 두 노드 사이의 경로(path)를 찾는 알고리즘을 구해 봅시다. 본 실습에서는 일단 경로가 사이클은 포함하지 않는 것으로 합니다. (즉, 경로에서 동일한 노드가 두 번 이상 들어가지 않는 것으로 합니다.). 따라서 경로(path)에 대해서는 교재에서 배운 정의에 더하여 사이클을 포함하지 않도록 한 다음의 정의를 사용합니다. 

### 정의 :   $n$ 을 음이 아닌 정수, $G$ 를 무방향 그래프라 하자.   그래프 $G$ 의 노드 $u$ 에서 노드 $v$ 로의 길이  $n$ 의 경로 는 $G$  의  $n$ 개 에지  $e_1, … , e_n $ 시퀀스로 ,    $i,j=0,1,…, n ~~$ 와  $i \neq j, x_{i} \neq  x_{j} $ 에 대해 에지  $e_i$ 는 $x_{i-1}$ 과  $x_i$ 를 끝점으로 갖으며,  노드 $x_0 = u, x_1, …,x_n-1 , x_n = v $  를 만족한다. 

#### 먼저, Connected Graph 에서 주어진 시작 노드와 종단 노드 간의 경로가 있으면 찾은 경로를 반환하는 알고리즘을 파이썬 프로그래밍해봅시다. 
#### 아래 경로 찾는 함수는 그래프의 인접 목록과  시작 노드, 종단 노드, 경로를 인수로 취하며, 처음 찾은 경로를 이 경로를 구성하는 노드 목록 리스트(시작 및 종단 노드 포함)를 반환합니다. 경로를 찾을 수 없으면 'None'을 반환합니다. 경로에서는 동일한 노드가 두 번 이상 들어가지 않는 것으로 합니다 (즉, 회로(사이클)는 포함하지 않습니다). 
#### 이 때, 경로는 인접 노드 에지들로 구성되므로 일련의 인접 노드 리스트로 구성되며, 노드가 경로에  2번 이상 들어가지 않는 것에 유의합니다.   

In [14]:
def find_path(graph, start, end, path=[]): #graph ;인접 노드 목록, start; 출발노드, end; 종단노드, path ; 경로
        path = path + [start] #  (1) 시작 노드를 경로에 추가
        
        if start == end: #(2)  경로가 종단 노드에 도달했는 지 점검
            return path
        if not start in graph : #(3)  start 노드가 그래프의 노드들 중 하나 인지를 점검 
            return None
        for node in graph[start]: # (4)start 노드 의 인접노드들에 대해서 'for' loop.
            #print(graph[start], node)
            for comp1 in node:   #  (5)
            #    print("comp1={}, node={}".format(comp1, node))    
                if comp1 not in path:  #(6) 인접노드가 경로에 없으면 수행
                    #print(comp1)
                    newpath = find_path(graph, comp1, end, path) #(7)인접노드가 경로에 없으면, 이 인접노드를 시작노드로하여 경로찾기를 다시 수행      행 
                    if newpath: 
                        return newpath
        return None 

![Alttext](fig11_Find_Paths.png)
- graph -> [그림 1]의 인접노드 리스트 표현, 
- start=’S’ , end=’F’ , path=[]
#### 1. 첫 루프 
(1) 시작 노드를 경로에 추가
   - path=path+[‘start’]  ==> path=[‘S’]
(2) 경로가 종점 노드에 도달했는 지 점검. 
    - 같으면 path 복귀 
    - 현재 start=’S’ , end=’F --> 같지 않음 
(3) start 가 그래프의 노드들 중의 하나인 지를 점검
    - start(현재는 ’S’) 가 그래프 노드들 중 하나가 아니면, 문제가 있으므로 
       ’None’ 복귀. 
    - 이 때 ‘graph' 는 dictionary 타입인데,  ‘graph' 의 키 들은 그래프의 노드
      들을 가르키며, 즉  'B', 'E', 'F', 'L',  'N', 'S' . 따라서,  ‘start(현재는 ’S’)’ 가  그래프의 노드들 중의 하나인 지를 점검.
    - start=‘S’ ∈ {'B', 'E', 'F', 'L',  'N', 'S'} 이므로 그래프 노드 들 중의 하나 
 (4) start 노드 의 인접노드들에 대해서 'for' loop
    - graph[‘S’]=['B', 'L', 'N']   
    - 따라서,   ‘for node in graph[start]: ’에서 node 는 'B', 'L', 'N' 가 순차적
      으로 됨. 첫 번째 경우  node=’B’
(5)  “for comp1 in node” ; node 에 있는  comp1 에 대해 루프 
    - 이 경우는 불필요한(redundant) 코드이나, 혹시 ‘node’ 가 컨테이너 타입인 
      경우를 대비하여 삽입된 코드
(6)  인접 노드가 경로에 없으면 수행
   ‘B’∉ path==[‘S’]
(7)  인접노드가 경로에 없으면, 이 인접노드를 시작노드로 하여 경로 찾기를 다시 수
     행 . 이때, start=’B’ end=’F’ , path=[‘S’] 
     
#### 2. 2번째 루프     
◦  start=’B’ end=’F’ , path=[‘S’] 

(1) 시작 노드를 경로에 추가
   - path=path+[‘start’]  ==> path=[‘S’, ‘B’]
(2) 경로가 종점 노드에 도달했는 지 점검. 
    - 같으면 path 복귀 
    - 현재 start=’B’ , end=’F --> 같지 않음 
(3) start 가 그래프의 노드들 중의 하나인 지를 점검
    - start(현재는 ’B’) 가 그래프 노드들 중 하나가 아니면, 문제가 있으므로 
       ’None’ 복귀. 
    - 이 때 ‘graph' 는 dictionary 타입인데,  ‘graph' 의 키 들은 그래프의 노드
      들을 가르키며, 즉  {'B', 'E', 'F', 'L',  'N', 'S'} . 따라서,  ‘start(현재는               ’S’ )가  그래프의 노드들 중의 하나인 지를 점검.
    - start=‘B’ ∈ {'B', 'E', 'F', 'L',  'N', 'S'} 이므로 그래프 노드 들 중의 하나  
 (4) start 노드(=‘B’)는 그래프 노드 들 중의 하나  의 인접노드들에 대해서 'for'           loop
    - graph[‘B’]=['F', 'L', 'N', 'S']   
    - 따라서,  ‘for node in graph[start]: ’에서 node 는 'F', 'L', 'N', 'S' 가 
      순차적으로 됨. 첫 번째 경우  node=’F’

(5)  “for comp1 in node” ; node 에 있는  comp1 에 대해 루프 
    - 이 경우는 불필요한(redundant) 코드이나, 혹시 ‘node’ 가 컨테이너 타입인 
      경우를 대비하여 삽입된 코드
(6)  인접 노드가 경로에 없으면 수행
  'F' ∉ path==[‘S’, ‘B’]
(7)  인접노드가 경로에 없으면, 이 인접노드를 시작노드로 하여 경로 찾기를 다시 수
     행 . 이때, start=’F’ end=’F’ , path=[‘S’, ‘B’] 


#### 3번째 루프 
◦  start=’F’ end=’F’ , path=[‘S’, ‘B’] 
(1) 시작 노드를 경로에 추가
   - path=path+[‘start’]  ==> path=[‘S’, ‘B’, ‘F’]
(2) 경로가 종점 노드에 도달했는 지 점검. 
    - 도달했으면 path 복귀 
    - 현재 start=’F’ , end=’F --> 같음 
    - 도달했으므로, path=[‘S’, ‘B’, ‘F’]

In [15]:
graph = {
       'B': ['F', 'L', 'N', 'S'],
       'E': ['F', 'L'],
       'F': ['B', 'E', 'L', 'N'],
       'L': ['B', 'E', 'F', 'N', 'S'],
       'N': ['B', 'F', 'L', 'S'],
       'S': ['B', 'L', 'N']  }


In [16]:
find_path(graph, 'S', 'F')

['S', 'B', 'F']

In [17]:
find_path(graph, 'S', 'N')

['S', 'B', 'F', 'E', 'L', 'N']

#### 처음 경로  찾는 상기 알고리즘은 인접 목록의 노드 리스트의 노드들의 순서에 따라 달라짐을 알 수있습니다.  

In [18]:
graph2 = {
       'B': [ 'L', 'F', 'N', 'S'],
       'E': ['F', 'L'],
       'F': ['B', 'E', 'L', 'N'],
       'L': ['B', 'E', 'F', 'N', 'S'],
       'N': ['B', 'F', 'L', 'S'],
       'S': ['B', 'L', 'N']  }


In [19]:
find_path(graph2, 'S', 'F')

['S', 'B', 'L', 'E', 'F']

#### 이제, 그래프를 인접 목록으로 표현하지 않고,  노드 집합 $V$ 및 에지 집합 $E$ 의 튜플  $G=(V,E)$ 로 표현하는 경우에, 처음 경로 를 찾는 파이썬 함수 코딩을 살펴 보기로 합시다.

In [20]:
V = {'B', 'E', 'F', 'L', 'N',  'S' }
E={('B', 'F'), ('B', 'L'), ('B', 'N'), ('B', 'S'),('E', 'F'),('E', 'L'), ('F', 'L'), ('F', 'N'), ('L', 'N'), ('L', 'S'), ('N', 'S')}
G2=(V, E)

In [21]:
def find_path2(graph, start, end, path=[]): #  G=(V,E) ; V 는 노드 집합 및 E 는 에지 집합으로 처리
        
        path = path + [start] #path 는 노드 리스트로 처리        
        V=graph[0]
        E=graph[1]                
       
        if start == end:
            return path
        if start not in V or end not in V:
            return None
        
        for edge in E: # node 는 노드 start 의 인접노드 리스트임
            if edge[0] ==start:                
                if edge[1] not in path:
                    NE=E-{edge}                                                        
                    new_graph=(V, NE)                    
                    newpath = find_path2(new_graph, edge[1], end, path)
                    if newpath:
                        return newpath
                else:
                    exit
            elif edge[1]==start:                   
                if edge[0] not in path:                
                    NE=E-{edge}                                     
                    new_graph=(V, NE)
                    newpath = find_path2(new_graph, edge[0], end, path)
                    if newpath:
                        return newpath
                else:
                    exit
        
        return None 

In [22]:
find_path2(G2, 'S', 'F')

['S', 'N', 'B', 'F']

In [23]:
def find_path3(graph, start, end, path=[]):       
        path = path + [start] #path 는 노드 리스트로 처리        
        V=list(graph[0]) #노드 집합을 노드 리스트로 변환 처리
        E=graph[1]            
        EL=list(E)
        EL.sort() # 에지 집합을  에지 리스트로 변환 처리
       
        if start == end:
            return path
        if start not in V or end not in V:
            return None
        
        for edge in EL: # node 는 노드 start 의 인접노드 리스트임
  
            if edge[0] ==start:                
                if edge[1] not in path:
                    NE=E-{edge}                                                        
                    new_graph=(V, NE)                    
                    newpath = find_path3(new_graph, edge[1], end, path)
                    if newpath:
                        return newpath
                else:
                    exit
            elif edge[1]==start:                   
                if edge[0] not in path:                    
                    NE=E-{edge}                                  
                    new_graph=(V, NE)
                    newpath = find_path3(new_graph, edge[0], end, path)
                    if newpath:
                        return newpath
                else:
                    exit
        
        return None 

In [24]:
find_path3(G2, 'S', 'F')

['S', 'B', 'F']

#### 이상의 코드 비교에서 그래프 에서 경로 찾는 문제의 경우에, 그래프 표현이 인접 목록인 경우가 $G=(V,E)$ 표현보다 보다 알고리즘이 간결해짐을 잘 알수 있습니다. 

###  다음은 그래프 표현이 인접 목록으로 주어질 때, 주어진 시작 노드와 종단 노드간의 모든 경로를 찾는 알고리즘입니다. 

In [25]:
def find_all_paths(graph, start, end, path=[]):
        path = path + [start] # (1) ; 경로 업데이트 
        if start == end:  # (2) 시작노드 와 종단 노드간 경로를 찾았는 지 점검
            return [path]  # 'find_all_paths'의 return  타입을 리스트의 리스트로 맞추기 위해, [path] 로 함
        if not start in graph : # (3) 시작노드가  그래프 노드 인지 점검
            return []
        all_paths = [] # (4) 모든 시작노드 와 종단 노드간의 모든 경로를 담는 경로(리스트 타입)의 리스트
        for node in graph[start]: # (5) 시작 노드의 인접 노드 탐색 
            if node not in path:
                newpaths = find_all_paths(graph, node, end, path) # (6) newpaths 는 해당 노드를 시작로 한 모든 경로들의 리스트
              #  print("NewPaths=", newpaths)
                for newpath in newpaths:  # (7) all_paths에  newpaths에 있는 모든 경로를 추가 
                    all_paths.append(newpath)
            # 이때 "all_paths" 는 graph[start] 에 있는 인접노드들중 처음부터 'node' 까지의 각각을 통과하는 '시작' 노드 및 '종단' 노드 까지의 
            # 의 경로들의 모임 
            # 따라서, 'start' 가 시작노드 이며, 'for' loop 동안 시작노드에서 시작노드에서 시작하여  시작노드의 인접노드들을 종단노드에 도달하는 
            # 모든 경로가  all_paths 에 포함됨
        return all_paths

#### $graph['S']= ['B', 'L', 'N'] $

In [26]:
find_all_paths(graph, 'S', 'F')

[['S', 'B', 'F'],
 ['S', 'B', 'L', 'E', 'F'],
 ['S', 'B', 'L', 'F'],
 ['S', 'B', 'L', 'N', 'F'],
 ['S', 'B', 'N', 'F'],
 ['S', 'B', 'N', 'L', 'E', 'F'],
 ['S', 'B', 'N', 'L', 'F'],
 ['S', 'L', 'B', 'F'],
 ['S', 'L', 'B', 'N', 'F'],
 ['S', 'L', 'E', 'F'],
 ['S', 'L', 'F'],
 ['S', 'L', 'N', 'B', 'F'],
 ['S', 'L', 'N', 'F'],
 ['S', 'N', 'B', 'F'],
 ['S', 'N', 'B', 'L', 'E', 'F'],
 ['S', 'N', 'B', 'L', 'F'],
 ['S', 'N', 'F'],
 ['S', 'N', 'L', 'B', 'F'],
 ['S', 'N', 'L', 'E', 'F'],
 ['S', 'N', 'L', 'F']]

###  다음은 그래프 표현이 $G=(V,E)$ 로 주어질 때, 주어진 시작 노드와 종단 노드간의 모든 경로를 찾는 알고리즘입니다. 

In [27]:
def find_all_paths2(graph, start, end, path=[]):       
        path = path + [start] #path 는 노드 리스트로 처리        
        V=list(graph[0]) #노드 집합을 노드 리스트로 변환 처리
        E=graph[1]            
        EL=list(E)
        EL.sort() # 에지 집합을  에지 리스트로 변환 처리
       
        if start == end:
            return [path]
        if start not in V or end not in V:
            return []
        
        all_paths=[]
       
        for edge in EL: # node 는 노드 start 의 인접노드 리스트임
  
            if edge[0] ==start:                
                if edge[1] not in path:
                    NE=E-{edge}
                    NNE=list(NE)
                    NNE.sort()                                     
                    new_graph=(V, NE)                    
                    newpaths = find_all_paths2(new_graph, edge[1], end, path)
                    for newpath in newpaths:
                        all_paths.append(newpath)
                else:
                    exit
            elif edge[1]==start:                   
                if edge[0] not in path:                    
                    NE=E-{edge}
                    NNE=list(NE)
                    NNE.sort()                   
                    new_graph=(V, NE)
                    newpaths = find_all_paths2(new_graph, edge[0], end, path)
                    for newpath in newpaths:
                        all_paths.append(newpath)
                else:
                    exit
        
        return all_paths

In [28]:
find_all_paths2(G2, 'S', 'F')

[['S', 'B', 'F'],
 ['S', 'B', 'L', 'E', 'F'],
 ['S', 'B', 'L', 'F'],
 ['S', 'B', 'L', 'N', 'F'],
 ['S', 'B', 'N', 'F'],
 ['S', 'B', 'N', 'L', 'E', 'F'],
 ['S', 'B', 'N', 'L', 'F'],
 ['S', 'L', 'B', 'F'],
 ['S', 'L', 'B', 'N', 'F'],
 ['S', 'L', 'E', 'F'],
 ['S', 'L', 'F'],
 ['S', 'L', 'N', 'B', 'F'],
 ['S', 'L', 'N', 'F'],
 ['S', 'N', 'B', 'F'],
 ['S', 'N', 'B', 'L', 'E', 'F'],
 ['S', 'N', 'B', 'L', 'F'],
 ['S', 'N', 'F'],
 ['S', 'N', 'L', 'B', 'F'],
 ['S', 'N', 'L', 'E', 'F'],
 ['S', 'N', 'L', 'F']]

In [29]:
len(find_all_paths(graph, 'S', 'F'))

20

In [30]:
find_all_paths2(G2, 'S', 'F')==find_all_paths(graph, 'S', 'F')

True

## 3. 최단 경로 찾기 
### 다음은 상기 [그림 1]에서 각 에지의 거리(weight)가 1 일때, 최단 경로를 찾는 알고리즘입니다.

#### 최단 경로 찾는 문제는 그래프의 인접 목록의 순서에 상관하지 않습니다. 

In [31]:
graph = {'B': ['F', 'L', 'N', 'S'],
        'E': ['F', 'L'],
        'F': ['B', 'E', 'N'],
        'L': ['B', 'E', 'F', 'N', 'S'],
        'N': ['B', 'F', 'L', 'S'],
        'S': ['B', 'L', 'N']}
graph2= {'S': ['B', 'L', 'N'],
       'B': ['L', 'N', 'S', 'F'],
       'L': ['B', 'E', 'F', 'N', 'S'],
       'N': ['B', 'F', 'L', 'S'],
       'E': ['F', 'L'],
       'F': ['B', 'E', 'N'] }

In [32]:
def find_shortest_path(graph, start, end, path=[]):        
        path = path + [start]  # (1)경로 업데이트
        if start == end:   # (2)경로가 주어진 시작노드로부터 주어진 종단노드 까지의 경로인지를 점검
            return path
        if not start in graph:  
            return None
        shortest = None  
        for node in graph[start]: #(3) 시작노드 의 인접노드 목록 의 노드들에 대한 'for' 루프            
            if node not in path:                
                newpath = find_shortest_path(graph, node, end, path) # (4)주어진 시작노드로부터 주어진 종단노드 까지의 경로가  newpath에               
                if newpath:
                    if not shortest or len(newpath) < len(shortest): #(5) 기존 최단 경로와 비교 
                        shortest = newpath                        
        return shortest

In [33]:
find_shortest_path(graph, 'S', 'F')

['S', 'B', 'F']

In [34]:
find_shortest_path(graph2, 'S', 'F')

['S', 'B', 'F']

In [35]:
find_shortest_path(graph, 'E', 'N')

['E', 'F', 'N']

In [36]:
find_shortest_path(graph2, 'E', 'N')

['E', 'F', 'N']

In [37]:
find_shortest_path(graph2, 'S', 'N')

['S', 'N']

In [38]:
def find_shortest_path2(graph, start, end, path=[], shortest=[]):
        path = path + [start]       
        if start == end:
            return path
        if not start in graph:
            return None
      
        for node in graph[start]:      
            if node not in path:                
                newpath = find_shortest_path2(graph, node, end, path, shortest)                
                if newpath:
                    if not shortest or len(newpath) < len(shortest):
                        shortest = newpath
                        
        return shortest

In [39]:
find_shortest_path2(graph, 'S', 'F')

['S', 'B', 'F']

In [40]:
find_shortest_path2(graph2, 'S', 'F')

['S', 'B', 'F']

In [41]:
find_shortest_path2(graph, 'E', 'N')

['E', 'F', 'N']

In [42]:
find_shortest_path2(graph2, 'E', 'N')

['E', 'F', 'N']

In [43]:
shortest=[]
def find_shortest_path3(graph, start, end, path=[]):
   
        path = path + [start]
        if start == end:
            return path
        if not start in graph:
            return None
        global shortest 

        for node in graph[start]:
            if node not in path:
                newpath = find_shortest_path3(graph, node, end, path)
                if newpath:
                    if not shortest or len(newpath) <= len(shortest):
                        shortest = newpath                   
        return shortest

In [44]:
find_shortest_path3(graph, 'S', 'F')

['S', 'N', 'F']

In [45]:
find_shortest_path3(graph, 'E', 'N')

['E', 'L', 'N']

In [46]:
find_shortest_path3(graph, 'S', 'F')

['S', 'N', 'F']

In [47]:
find_shortest_path3(graph2, 'E', 'N')

['E', 'L', 'N']

### 상기 알고리즘에서 최단 경로가 여러 개가 있더라도 처음 찾아지는 최단 경로를 복귀합니다. 

In [48]:
find_shortest_path3(graph, 'S', 'F')

['S', 'N', 'F']

### 이제, [그림 2]과 같이 에지에 다양한 거리(weight)를 갖는 그래프에서 경로 찾는 문제의 경우에서, 자료 구조 표현 및 알고리즘 등을 살펴보기로 합니다,
![Alttext](fig11-2.png)

#### 다음과 같이 상기 adjacency list 에 에지 거리(weigth)를 추가한 가중치 adjacency list 를 고려해봅시다.

In [49]:
graph_w = {'S': [['B', 175], ['L', 125],['N', 320]],
             'B': [['F', 245], ['L', 115], ['N', 145], ['S', 175]],
             'L': [['B', 115], ['E', 645],['F', 220],['N', 260],['S', 125]],
             'N': [['B', 145], ['F', 385],['L', 260],['S', 320]],
             'E': [['F', 450],['L', 645]],
             'F': [['B', 245], ['E', 450],['N', 385]]}


#### [그림 2]의 그래프를 상기 weighted adjacency list 로 표현한 경우에, 경로 찾기 알고리즘은 다음과 같이 표현 자료구조에 따라 약간의 변형이 필요합니다. 

In [50]:
def find_path_w(graph, start, end, path=[]):
        path = path + [start]
        
        if start == end:
            return path
        if not start in graph:
            return None
        for node in graph[start]: #  node는 graph[start] 의 한 료소. 예; graph['S']라면, graph['S']=[['B', 175], ['L', 125],['N', 320]]
            #node= ['B', 175], or  []'L', 125], or ['N', 320]
            if node[0] not in path: #node[0]='B' or 'L' or 'N'
                newpath = find_path_w(graph, node[0], end, path) #node[0] 를 시작노드로 하여 재귀적으로 함수 호출 
                if newpath: return newpath
        return None 


In [51]:
find_path_w(graph_w, 'S', 'F')

['S', 'B', 'F']

#### [그림 2]경우에, 시작노드에서 종단노드까지의 모든 경로를 찾아 봅시다. 

In [52]:
def find_all_paths_w(graph, start, end, path=[]):
        path = path + [start]
        if start == end:
            return [path]        
        if not start in graph:
            return []  
        
        all_paths = []
        for node in graph[start]: #graph['S']=[['B', 175], ['L', 125],['N', 320]] #node=['B', 175]
            if node[0] not in path:        
                newpaths = find_all_paths_w(graph, node[0], end, path)
                for newpath in newpaths:
                    all_paths.append(newpath)
        return all_paths

In [53]:
find_all_paths_w(graph_w, 'S', 'F')

[['S', 'B', 'F'],
 ['S', 'B', 'L', 'E', 'F'],
 ['S', 'B', 'L', 'F'],
 ['S', 'B', 'L', 'N', 'F'],
 ['S', 'B', 'N', 'F'],
 ['S', 'B', 'N', 'L', 'E', 'F'],
 ['S', 'B', 'N', 'L', 'F'],
 ['S', 'L', 'B', 'F'],
 ['S', 'L', 'B', 'N', 'F'],
 ['S', 'L', 'E', 'F'],
 ['S', 'L', 'F'],
 ['S', 'L', 'N', 'B', 'F'],
 ['S', 'L', 'N', 'F'],
 ['S', 'N', 'B', 'F'],
 ['S', 'N', 'B', 'L', 'E', 'F'],
 ['S', 'N', 'B', 'L', 'F'],
 ['S', 'N', 'F'],
 ['S', 'N', 'L', 'B', 'F'],
 ['S', 'N', 'L', 'E', 'F'],
 ['S', 'N', 'L', 'F']]

#### 다음은 [그림 2]에서  최단 경로와 그 때의 최단 경로 길이를 찾는 알고리즘입니다.

In [54]:
from math import *
def find_shortest_path_w(graph, start, end, path=[], distance=0):
        path = path+ [start]            
        if start == end:
            return path, distance
        if not start in graph:
            return None, inf
        
        shortest_path = None
        shortest_path_distance = inf #inf=무한대

        for node in graph[start]: #graph['S']=[['B', 175], ['L', 125],['N', 320]] #node=['B', 175]
            if node[0] not in path:   #node[0]='B'             
                distance= distance+node[1]  #node[1]=175 
                
                new_path, new_path_distance = find_shortest_path_w(graph, node[0], end, path, distance)
                distance=distance-node[1] #한 단계 위로 올라가 다시 게산하여야 해서 
                if new_path:
                    if not shortest_path or new_path_distance < shortest_path_distance:
                        shortest_path = new_path
                        shortest_path_distance = new_path_distance
        return shortest_path, shortest_path_distance

In [55]:
find_shortest_path_w(graph_w, 'S', 'F')

(['S', 'L', 'F'], 345)

In [56]:
find_shortest_path_w(graph_w, 'N', 'E')

(['N', 'F', 'E'], 835)

## 4. 오일러 경로(Euler Path) 찾기

### 오일러 경로는 그래프의 모든 에지를 한 번씩만 통과하면서 방문하는 경로로, circuit 은 아닙니다. 그래프에 홀수점이 없으면, 아무른 짝수점에서 출발하여 그래프의 각 에지들을 거쳐 다시 해당 출발 짝수점으로 복귀할 수있습니다  이 경우에 오일러 회로라고 합니다.  오일러 경로는 홀수점이 2개가 있어야만, 오일러 경로의 존재가 보장됩니다. 따라서, 1개의 홀수점에서 시작해서 다른 홀수점에서 끝나야 합니다.  따라서,  시작 홀수ㅈ점에서 출발하여 circuit 이 있으면 circuit 에지들을 순회하여 다른 종단 홀수점으로 방문해가야 합니다. 이러한 아이디어를 기반으로 오일러 경로는 다음과 같은 절차로 구합니다.

#### 1) 주어진 그래프에서 홀수점의 갯수를 찾는다. 홀수점이  2개가 아니면 오일러 경로는 없습니다. 홀수점이 2개인 경우에 2개 중 하나는 시작노드로 다른 하나는 종단노드로 구성합니다. 이후 다음의 과정을 거침니다. 
#### 2) 주어진 그래프에서 시작노드에서 시작하여 종단노드까지의 시작-종단 경로(백본경로)를 찾습니다.
#### 3) 그래프에서  이 경로 또는 순환경로(circuit)에 있는 에지들은 제거한 남은 그래프를 만듬니다.
#### 4) 남은 그래프에 대해 시작-종단 백본 경로에 있는 각 노드에 대해 순환 경로(circuit)가 있으면  찾습니다. 
#### 5) 남은 그래프에서 남은 에지가 없어질 때까지  3)과 4)의 과정을 되풀이 합니다. 
#### 6) 이때, 오일러 경로는 백본 경로의 시작 노드. 시작노드에서의 순환 경로들, 백본 시작노드에서 백본의 다음 중간 노드까지 경로, 이 백본 중간노드들에서의 순환 경로들,  백본 중간노드에서 백본 다음 중간노드까지의 경로, 이 백본 중간노드에서의 순환경로, ... , 백본 중간노드에서 백본 종단노드까지의 경로,  종단노드에서의 순환 경로들 로 구성됩니다. 

![alt text](fig11-3.png)  

#  

### 상기 [그림 3]의  그래프를 예제로 오일러 경로 알고리즘을 살펴 보기로 합니다.  
#### 그래프를 표현하는 방법으로는 다음과 같이 adjacency list를 사용하며,  파이썬에서는 adjacency list를 dictionary 로 표현한 것이 유용하는 것을 이미 학습했습니다.  
####  (예 ; [그림 3] 그래프 경우)
~~~python
graph_E = {'B': ['F', 'L', 'N', 'S'],
       'E': ['F', 'L'],
       'F': ['B', 'E', 'N'],   
       'L': ['B', 'E', 'N', 'S'],
       'N': ['B', 'F', 'L', 'S'],       
       'S': ['B', 'L', 'N'],}.
~~~
 
### 그래프의 에지는 에지를 구성하는 2개의 노드(vertex) 쌍 의 튜플(tuple) 로 표현할 수 있습니다. 
#### 즉, 상기 [그림 3]에서 노드 'S' 와 노드 'N' 을 연결하는 에지는 ('S', 'N') 으로 표현한다.  이때, 노드쌍 튜플의 첫번째  노드 'S'들 시작노드 , 두번째 노드 'N' 을 종단 노드로 간주하는 경우에 이 에지를 방향성 에지라 하며, 이를 구분하지 않는 경우를 비방향성 에지라 한다. 방향성 에지에서는 ('S', 'N') 와 ('N', 'S' ) 는 다른 에지이나,  비방향성 에지에서는 둘다 같은 에지이다.


### 1) 그래프에서 홀수점 찾기 

In [57]:
def find_odd_points(graph):
    odds=[]
    for i in graph:
        if len(graph[i])%2 != 0:
            odds.append(i)
    return odds        

#### 상기 홀수점 찾는 함수가 제대로 동작하는 지를 점검해 봅시다.  

In [58]:
fig3_graph = {
       'B': ['F', 'L', 'N', 'S'],
       'E': ['F', 'L'],
       'F': ['B', 'E', 'N'],
       'L': ['B', 'E',  'N', 'S'],
       'N': ['B', 'F', 'L', 'S'],       
       'S': ['B', 'L', 'N']  }

In [59]:
odds=find_odd_points(fig3_graph)
start_odd_point = odds[0]
end_odd_point = odds[1]
print("start_odd_point=", start_odd_point)
print("end_odd_point=", end_odd_point)

start_odd_point= F
end_odd_point= S


### 2) 주어진 그래프에서 시작노드에서 시작하여 종단노드까지의 시작-종단 경로(백본경로) 찾기.

In [60]:
def find_shortest_path2(graph, start, end, path=[], shortest=[]):
        path = path + [start]       
        if start == end:
            return path
        if not start in graph:
            return None
      
        for node in graph[start]:      
            if node not in path:                
                newpath = find_shortest_path2(graph, node, end, path, shortest)                
                if newpath:
                    if not shortest or len(newpath) < len(shortest):
                        shortest = newpath
                        
        return shortest

In [61]:
odds=find_odd_points(fig3_graph)
print("odds[0]=", odds[0])
print("odds[1]=", odds[1])
backbone_path=find_shortest_path2(fig3_graph, odds[0], odds[1])
print(backbone_path)    

odds[0]= F
odds[1]= S
['F', 'B', 'S']


### 3) 그래프에서  경로 또는 순환경로(circuit)에 있는 에지들은 제거한 남은 그래프 생성하기

In [62]:
def remove_path_from_graph(graph, path):
    if len(path) < 2:
        return graph
    for i in range(len(path)-1):       
        if path[i+1] in graph[path[i]]:
                graph[path[i]].remove(path[i+1])
        if path[i] in graph[path[i+1]]:
                graph[path[i+1]].remove(path[i])
                
    return graph            

In [63]:
odds=find_odd_points(fig3_graph)
print("odds[0]=", odds[0])
print("odds[1]=", odds[1])
backbone_path=find_shortest_path2(fig3_graph, odds[0], odds[1])
print("Backbone path=", backbone_path)    
fig4_graph=remove_path_from_graph(fig3_graph, backbone_path)
print("Figure_4 graph=", fig4_graph)

odds[0]= F
odds[1]= S
Backbone path= ['F', 'B', 'S']
Figure_4 graph= {'B': ['L', 'N'], 'E': ['F', 'L'], 'F': ['E', 'N'], 'L': ['B', 'E', 'N', 'S'], 'N': ['B', 'F', 'L', 'S'], 'S': ['L', 'N']}


#### 상기 결과는 [그림 3] 그래프에서 백본 경로 [ 'F', 'B', 'S'] 가 제거된, 다음 [그림 4] 그래프 표현입니다.
![alt text](./fig11-4.png)

### 4) 그래프의 노드에 대해 순환 경로(circuit)가 있으면  찾기

In [64]:
def find_circuit(graph, start, end, circuit=[]):
        circuit = circuit+ [start]
        if len(circuit) > 3 and start == end:
#        ('S', 'L', 'S' ) 같은 경우를 배제하기 위해, "len(circuit) > 3 " 사용
           return circuit
        if not start in graph:
            return None
        for node in graph[start]:
            for comp1 in node:
                if comp1 not in circuit or (len(circuit) >2 and (comp1==end)):
                    newcircuit = find_circuit(graph, comp1, end, circuit)
                    if newcircuit: return newcircuit
        return None 

In [65]:
print(fig4_graph)
circuit_s=find_circuit(fig4_graph, 'F', 'F')
print("Circuit at 'F'=", circuit_s)

{'B': ['L', 'N'], 'E': ['F', 'L'], 'F': ['E', 'N'], 'L': ['B', 'E', 'N', 'S'], 'N': ['B', 'F', 'L', 'S'], 'S': ['L', 'N']}
Circuit at 'F'= ['F', 'E', 'L', 'B', 'N', 'F']


#### 상기 출력된 circuit ['F', 'E', 'L', 'B', 'N', 'F'] 는 다음 [그림 5]의 빨간색 회로 부분입니다.
![Altext](./fig11-5.png)

#### [그림 5]에서 빨간색 부분 에지를 제거하면 다음과 [그림 6]의 그래프이며, 이 그래프의 표현은 
{S': [], 'B': [], 'L': ['E', 'N'], 'N': ['F', 'L'], 'E': ['F', 'L'], 'F': ['E', 'N']}
![Altext](./fig11-6.png) 이고, 이 그래프 표현은 다음과 같이 구합니다.  

In [66]:
fig6_graph=remove_path_from_graph(fig4_graph, circuit_s)
print(fig6_graph)


{'B': [], 'E': [], 'F': [], 'L': ['N', 'S'], 'N': ['L', 'S'], 'S': ['L', 'N']}


#### 여기서 계속, 남아 있는 그래프, [그림 6] 에서 순회 경로를 찾아 보면  다음과 같습니다. 

In [67]:
circuit_f=find_circuit(fig6_graph, 'S', 'S')
print("Circuit at 'S'=", circuit_f)

Circuit at 'S'= ['S', 'L', 'N', 'S']


#### 이제, 이상 각 구현된 함수들을 이용하여 오일러 경로 찾기 함수를 구현한 결과는 다음과 같습니다. 

In [68]:
def find_Euler_path(graph):
    circuit=[]
    add_circuit=[]
    path=[]
    Euler_path=[]
    temp=True
    odds=find_odd_points(graph)
    print("odds=", odds) 
    if len(odds)!= 2:        
        print("No Euler path Exists")
        return
        
    Euler_path=find_shortest_path2(graph, odds[0], odds[1])
    print("Backbone Path", Euler_path) 
    
    graph=remove_path_from_graph(graph, Euler_path)
    
    path = Euler_path.copy()
    
    for i in range(len(path)):
        while temp==True:
            add_circuit=find_circuit(graph, path[i], path[i]) 

            if add_circuit: 
                if len(circuit)>1 and circuit[-1]==add_circuit[0]:
                    circuit=circuit[0:-1]+add_circuit
                else:    
                    circuit=circuit+add_circuit
                graph=remove_path_from_graph(graph, add_circuit)
                temp=True
            else:
                temp=False
        if circuit:
            Euler_path[i]=circuit 
        circuit=[] 
        temp=True
    return Euler_path    

In [69]:
fig3_graph = {
       'B': ['F', 'L', 'N', 'S'],
       'E': ['F', 'L'],
       'F': ['B', 'E', 'N'],
       'L': ['B', 'E',  'N', 'S'],
       'N': ['B', 'F', 'L', 'S'],       
       'S': ['B', 'L', 'N']  }

In [70]:
find_Euler_path(fig3_graph)

odds= ['F', 'S']
Backbone Path ['F', 'B', 'S']


[['F', 'E', 'L', 'B', 'N', 'F'], 'B', ['S', 'L', 'N', 'S']]

#### 상기 결과 출력값은 홀수점 'F'에서 시작하여 'B', 'S' 순으로 백본 경로를 진행할 때, 각 백본 경로의 시작 노드점 'ㄹ' 에서의 순환 경로 ['F', 'E', 'L', 'B', 'N', 'F'], 백본 경로의 중간노드, 'B', 백본 경로의 종단노드 'S' 에서의 순환 경로 ['S', 'L', 'N', 'S'] 로 구성된 오일러 경로를 나타냅니다.
![Altext](./fig11-7.png)

## 5. 'networkx'  패키지를 활용한 그래프 문제 풀기 

### Graph 다루는 파이썬 패키지로 'networkx' (https://networkx.github.io/) 가 있습니다.   

'networkx' 패키지 활용 참고 자료 : http://pythonkr.github.io/pyconkr-2014/pdf/pyconkr-2014-07_networkx.pdf

#### 이를 이용하여 그래프 문제를 풀어 봅시다.

In [71]:
import networkx as nx # networkx 패키지 임포트

In [72]:
G=nx.Graph()
Nodes=['S', 'B', 'L', 'N', 'E', 'F' ]
G.add_nodes_from(Nodes)

# adding a list of edges:
G.add_edges_from([('S', 'L'), ('S', 'B'), ('S', 'N'), ('B', 'F'), ('B', 'L'), ('B', 'N'), ('L', 'E'), ('L', 'F'), ('L', 'N'), 
                   ('N', 'F'), ('E', 'F') ])
print("Nodes of graph: ")
print(G.nodes())
print("Edges of graph: ")
print(G.edges())

Nodes of graph: 
['S', 'B', 'L', 'N', 'E', 'F']
Edges of graph: 
[('S', 'L'), ('S', 'B'), ('S', 'N'), ('B', 'F'), ('B', 'L'), ('B', 'N'), ('L', 'E'), ('L', 'F'), ('L', 'N'), ('N', 'F'), ('E', 'F')]


#### 'S' 노드와 연결되어 있는 노드는 아래 코드로 찾을 수 있다.

In [73]:
print(G['S'])

{'L': {}, 'B': {}, 'N': {}}


#### 'networkx' 패키지에서 경로 찾기는 다음과 같이 찾습니다.

In [74]:
list(nx.all_simple_paths(G, "S", "F"))

[['S', 'L', 'B', 'F'],
 ['S', 'L', 'B', 'N', 'F'],
 ['S', 'L', 'E', 'F'],
 ['S', 'L', 'F'],
 ['S', 'L', 'N', 'B', 'F'],
 ['S', 'L', 'N', 'F'],
 ['S', 'B', 'F'],
 ['S', 'B', 'L', 'E', 'F'],
 ['S', 'B', 'L', 'F'],
 ['S', 'B', 'L', 'N', 'F'],
 ['S', 'B', 'N', 'L', 'E', 'F'],
 ['S', 'B', 'N', 'L', 'F'],
 ['S', 'B', 'N', 'F'],
 ['S', 'N', 'B', 'F'],
 ['S', 'N', 'B', 'L', 'E', 'F'],
 ['S', 'N', 'B', 'L', 'F'],
 ['S', 'N', 'L', 'B', 'F'],
 ['S', 'N', 'L', 'E', 'F'],
 ['S', 'N', 'L', 'F'],
 ['S', 'N', 'F']]

In [75]:
len(list(nx.all_simple_paths(G, "S", "F")))

20

In [76]:
paths=list(nx.all_simple_paths(G, "S", "F"))
paths.sort()
paths

[['S', 'B', 'F'],
 ['S', 'B', 'L', 'E', 'F'],
 ['S', 'B', 'L', 'F'],
 ['S', 'B', 'L', 'N', 'F'],
 ['S', 'B', 'N', 'F'],
 ['S', 'B', 'N', 'L', 'E', 'F'],
 ['S', 'B', 'N', 'L', 'F'],
 ['S', 'L', 'B', 'F'],
 ['S', 'L', 'B', 'N', 'F'],
 ['S', 'L', 'E', 'F'],
 ['S', 'L', 'F'],
 ['S', 'L', 'N', 'B', 'F'],
 ['S', 'L', 'N', 'F'],
 ['S', 'N', 'B', 'F'],
 ['S', 'N', 'B', 'L', 'E', 'F'],
 ['S', 'N', 'B', 'L', 'F'],
 ['S', 'N', 'F'],
 ['S', 'N', 'L', 'B', 'F'],
 ['S', 'N', 'L', 'E', 'F'],
 ['S', 'N', 'L', 'F']]

In [77]:
paths==find_all_paths(graph, 'S', 'F')

True


#### 'networkx' 패키지에서 최단 경로는 다음과 같이 찾습니다.

In [78]:
nx.shortest_path(G, 'S', 'F', 'weight')

['S', 'L', 'F']

## 실습 문제 

###  실습 1. 
####  가중치가 없는 그래프 표현이 $G=(V,E)$ 로 주어자는 경우에, 주어진 source node 와 destination node 간의 최단 경로를 찾는 파이썬 함수를 코딩하여 보시오. 
#### 또한, 이 경우에 [그림 1]에 대하여, 노드 'E' 에서 노드 'N' 까지의 최단 경로, shortest_path 를 구하고, 출력이 "The shortest path from node 'E' to node 'N' = shortest_path " 로 나오도록 해보시오.

###  실습 2.
#### 실습 1의 파이썬 함수를 활용하여, 주어진 그래프의 각 노드 간의 최단 경로를 구해보시오. 단, 2개 노드 $v_i, v_j $ 쌍에 대해서,  2 노드간의 최단 경로는 노드 $v_i $ 에서 $v_j$ 의 최단 경로만을 구하고,  $v_j $ 에서 $v_i$ 는 구하지 마시오. 즉 2개 노드 쌍 간의 최단 경로는 알파벳ㅅ이 작은 노드에서 큰 노드간의 최단 경로만을 구합니다. 

### 실습  3, 4. 
#### 다음과 같은 그래프가 주어진다고 하자.</h3>
![Alttext](11-exer.png)

### 실습 3.
#### "networkx' 파이썬 패키지를 사용하지 말고, 노드 F 에서 각 노드 B, C, D, H, G 까지의 최단 경로와 최단 거리를 구하는 파이썬 프로그래밍을 해보시오.


※ 풀이조건
<ol>
    <li><b>직접 프로그래밍을 하여</b> 시작 노드를 F로, 도착 노드를 B, C, D, H, G 중 하나씩 설정해서 총 5개의 최단 경로와 최단 거리를 구하여 출력한다.(예: (F-B), (F-C), (F-D), (F-H), (F-G) 로, 총 5개)</li>
    <li>최단 경로가 2개 이상일 경우 아무 것이나 1개를 택하여 출력한다.</li>
</ol>
<br/> ※ 제한조건
<ol>
    <li>5개 경로 및 거리가 모두 올바른 값이면 정답 처리 한다.</li>
    <li>코드 내 import 문을 사용할 경우 0점 처리한다. <b>위 실습 코드 중 'from math import *'을 그대로 사용하지 않도록 주의한다.</b></li>
</ol>


### 실습 4.
#### 그래프 이론을 공부했던 이산이는 문득 지금까지 배웠던 최단 거리 말고 최장 거리를 구하려면 어떻게 해야하는 지 궁금했다, 이를 위해 이산이는 반 친구들의 이름을 빌려 아래처럼 그래프를 그려보았다.

<b>노드 정보</b>
<br/>'노리', '새롬', '나래', '하은', '시내', '아름', '푸름', '마루', '하랑', '진운', '영현', '이산'

<b>엣지(거리) 정보</b>
<br/>[('나래', '영현', 1), ('하은', '하랑', 8), ('하랑', '진운', 1), ('시내', '마루', 7), ('나래', '진운', 2), ('푸름', '하랑', 5), ('새롬', '영현', 7), ('새롬', '시내', 8), ('노리', '아름', 3), ('나래', '하은', 9), ('하은', '아름', 3), ('나래', '마루', 4), ('시내', '푸름', 6), ('하은', '시내', 3), ('노리', '시내', 4), ('푸름', '진운', 7), ('아름', '푸름', 2), ('새롬', '하랑', 7), ('푸름', '영현', 0),
 ('아름', '마루', 6), ('노리', '이산', 7), ('새롬', '나래', 1), ('하은', '마루', 10), ('나래', '아름', 1), ('아름', '이산', 10), ('노리', '하랑', 8), ('영현', '이산', 2), ('시내', '하랑', 6), ('노리', '새롬', 9), ('노리', '마루', 4), ('마루', '이산', 8), ('새롬', '푸름', 9), ('새롬', '하은', 8), ('아름', '하랑', 8), ('나래', '시내', 7), ('새롬', '마루', 3), ('노리', '진운', 4), ('아름', '영현', 9),
 ('노리', '푸름', 5), ('시내', '진운', 1), ('새롬', '이산', 3), ('나래', '이산', 4), ('시내', '이산', 4), ('하은', '이산', 10)]

![prob4](fig11-prob4.png)

<br/>위 그래프에서 각 노드 간 엣지는 친구 관계를 나타내며 거리 값은 친밀도를 나타낸다. (높을수록 서로 더 친밀하다)
<br/>이산이는 최대 2명의 친구를 거쳐 새로운 친구를 소개받고 싶다고 했을 때 서로 서로 매우 친한 사이였으면 좋겠다고 생각했다.
<br/>현재 이산이와 친구 관계를 맺지 않은 반 친구들을 찾고 어떤 친구에게 소개를 받아야 하는 지 파이썬 프로그래밍을 통해 구하시오.

하은이에게 진운이를 소개할 경우 출력 예시는 아래와 같다.
<br/><b>"하은에게 진운을 소개하려면 ['새롬', '푸름'] 를 거쳐야 한다. 이때 친밀도(거리값)는 24 으로 가장 높다."</b>

※ 풀이조건
<ol>
    <li>시작 노드를 '이산'으로, 도착 노드들을 '이산과 친구 관계가 아닌' 노드로 하고 각 도착 노드에 대해 어떤 친구를 거쳐 소개를 받아야 하는 지 출력한다.</li>
    <li><b>최대 2명</b>의 친구를 거쳐야 하며, 친구 관계가 아닌 친구를 거쳐서 소개를 받을 수 없다.</li>
</ol>
<br/> ※ 제한조건
<ol>
    <li>이산이와 친구 관계가 아닌 친구들을 찾을 때 반드시 프로그래밍을 통해 찾을 필요는 없다.</li>
    <li>2명보다 많은 친구들을 거칠 경우 0.5점 감점한다.</li>
    <li>기타 제한은 없다.(라이브러리 자유롭게 사용)</li>
</ol>
